server:
  port: 8080

  address: 127.0.0.1

spring:
  datasource: #数据库连接
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/web_experiment
    username: root
    password: 123456
  servlet:
    multipart:  #文件上传
      max-file-size: 10MB #配置单个文件上传大小限制
      max-request-size: 100MB #配置单次请求最大上传大小的限制

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #配置mybatis的日志，指定输出到控制台
    map-underscore-to-camel-case: true  #配置mybatis的驼峰命名自动映射开关